# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QC6qXLgSiq3NgNOUaN2jDlO_9Os3Ozfj
"""

import random

class Dado:
    def __init__(self):
        self.cara = 6

    def lanzar_dado(self):
        resultado = random.randrange(self.cara) + 1
        return resultado
# COLABORACION ENTRE OBJETOS
class Dados:
    def __init__(self):
        self.caras = Dado()
    
    def lanzar_dados(self):
        dado1 = self.caras.lanzar_dado()
        dado2 = self.caras.lanzar_dado()
        return dado1 + dado2

dice = Dados()
print(dice.lanzar_dados())

dado1 = Dado()
print(dado1.lanzar_dado())

class Alumno:
    def __init__(self,nombre, curso, direccion = None):
        self.nombre = nombre
        self.curso = curso
        self.direccion = direccion 
    
    def mostrar_datos(self):
        print(f'Nombre Alumno: {self.nombre} \n Curso: {self.curso} \n Direccion: {self.direccion}')
# COMPOSICION ENTRE OBJETOS
class Direccion:
    def __init__(self, calle, ciudad):
        self.calle = calle
        self.ciudad = ciudad

direccion_alumno = Direccion('Avnida siempre viva 742','Springfield')

alumno1 = Alumno('Bart Simpson', 'Fullstack Python', direccion_alumno)
alumno1.mostrar_datos()
dir(alumno1.direccion)
alumno1.direccion.calle
alumno1.direccion.ciudad

