# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QC6qXLgSiq3NgNOUaN2jDlO_9Os3Ozfj
"""

class Perro:
    def desplazar(self):
        print('Yo me muevo caminando...')

class Pajaro:
    def desplazar(self):
        print('Yo me muevo volando...')

class Pez:
    def desplazar(self):
        print('Yo me muevo nadando...')

# AQUI ESTA LA MAGIA DEL POLIMORFISO, SI HAY UN COMPORTAMIENTO PARECIDO (DESPLAZAR)
# SE ALMACENA EN UN NUEVO METODO, DONDE LUEGO SE PUEDE LLAMAR
def desplazar_animal(animal):
    animal.desplazar()


animal1 = Perro()
animal2 = Pajaro()
animal3 = Pez()
desplazar_animal(animal3)





